################################# BASIC INPUTS (required for all runs) ####################################

# Required work/organizational files. 
WORKDIR: /tscc/lustre/ddn/scratch/YOUR_USERNAME/skipper100_test
MANIFEST: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/example/yeo_lab_internal_example_manifest.csv
TOOL_DIR: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/tools

# Required Annotation Files
GFF_SOURCE: "gencode" # One of either "gencode" or "ensembl". 
GFF: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/annotations/gencode.v38.annotation.gff3.gz
GENOME: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/annotations/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta ###!!!### REPLACE WITH CORE TSCC PATH
ACCESSION_RANKINGS: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/annotations/accession_type_ranking.txt
BLACKLIST: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/annotations/encode3_eclip_blacklist.bed # set to None for no blacklist

# Auto Generated Annotation Files.
# MUST still specify paths/names so skipper knows where to save generated files to!
PARTITION: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/annotations/gencode.v38.annotation.tiled_partition.bed.gz
FEATURE_ANNOTATIONS: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/annotations/gencode.v38.annotation.tiled_partition.features.tsv.gz
STAR_DIR: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/annotations/gencode.v38_star_ref

# eCLIP Parameters
protocol: ENCODE4 # ENCODE4 for single end, ENCODE3 for paired end.
UMI_SIZE: 10
INFORMATIVE_READ: 1
OVERDISPERSION_MODE: input   # input or clip, input is reccomended
GINI_CUTOFF: 0.9

################################# ADVANCED INPUTS (required for additional analyses) ####################################

HOMER: True # Required for ml analysis (False or missing will be overwritten if ml is specified)
META_ANALYSIS: True # Usually not required. 

# Repeat analysis. Leave blank to only perform analysis on non-repetitive regions. 
REPEAT_TABLE: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/annotations/repeatmasker.grch38.tsv.gz
REPEAT_BED: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/annotations/repeatmasker.grch38.sort.unique.bed.gz # Can be auto generated by Skipper!!!

# Gene set analysis. Leave blank to skip gene set analysis. 
GENE_SETS: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/annotations/c5.go.v7.5.1.symbols.gmt
GENE_SET_REFERENCE: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/annotations/encode3_go_terms.reference.tsv.gz
GENE_SET_DISTANCE: /tscc/projects/ps-yeolab4/software/skipper/1.100.0/bin/skipper/annotations/encode3_go_terms.jaccard_index.rds