verbose: false
printshellcmds: true
notemp: false 
latency: 60
skip-script-cleanup: true
retries: 3
nolock: true
default-storage-provider: none
rerun-triggers: mtime
keep-going: true
use-conda: true
conda-prefix: "/tscc/nfs/home/$USER/scratch/snakeconda/"
conda-frontend: conda
rerun-incomplete: true
jobs: 8
executor: local
default-resources:
  runtime: 30
  mem_mb: 20000
use-envmodules: true
show-failed-logs: true
