verbose: false
notemp: true
latency: 60
printshellcmds: true
skip-script-cleanup: true
nolock: true
keep-going: true
use-singularity: true
singularity-args: "--bind /tscc"
singularity-prefix: /tscc/nfs/home/hsher/scratch/singularity
use-conda: true
conda-prefix: "/tscc/nfs/home/hsher/snakeconda"
conda-frontend: conda
jobs: 8