verbose: false
quiet: reason
printshellcmds: true
notemp: true
latency: 60
skip-script-cleanup: true
retries: 1
nolock: true
default-storage-provider: none
rerun-triggers: software-env
keep-going: true
use-conda: true
conda-prefix: "/tscc/nfs/home/kflanagan/snakeconda"
conda-frontend: conda
rerun-incomplete: true
jobs: 30
executor: slurm
default-resources:
  slurm_partition: "gold"
  slurm_account: "csd792"
  runtime: 30
  mem_mb: 20000
  slurm_extra: "--qos=hcg-csd792 --exclude=tscc-1-8,tscc-13-34"