verbose: false
printshellcmds: false
notemp: true
latency: 60
printshellcmds: true
skip-script-cleanup: true
nolock: true
keep-going: true
use-singularity: "true"
singularity-args: "--bind /tscc --nv"
singularity-prefix: /tscc/nfs/home/hsher/scratch/singularity
use-conda: true
conda-prefix: "/tscc/nfs/home/hsher/snakeconda"
conda-frontend: conda
rerun-incomplete: true
jobs: 30
executor: slurm
default-resources:
  slurm_partition: "gold"
  slurm_account: "csd792"
  runtime: 30
  mem_mb: 20000
  slurm_extra: "--qos=hcg-csd792 --exclude=tscc-14-46,tscc-1-3,tscc-1-15,tscc-1-2,tscc-1-41,tscc-4-15,tscc-8-35"
set-resources:
  rbpnet_variants_score_fa:
    slurm_partition: "rtx3090"
    slurm_account: "csd792"
    slurm_extra: "'--qos=condo-gpu' '--gpus=1'"
    runtime: 1