verbose: false
quiet: reason
printshellcmds: true
notemp: true
latency: 60
skip-script-cleanup: true
retries: 3
nolock: true
keep-going: true
use-conda: true
conda-prefix: "/tscc/nfs/home/kflanagan/snakeconda"
conda-frontend: conda
rerun-incomplete: true
jobs: 30
executor: slurm
default-resources:
  slurm_partition: "gold"
  slurm_account: "csd792"
  runtime: 30
  mem_mb: 20000
  slurm_extra: "--qos=hcg-csd792 --exclude=tscc-1-16"
# set-resources:
#   rbpnet_variants_score_fa:
#     slurm_partition: "rtx3090"
#     slurm_account: "csd792"
#     slurm_extra: "'--qos=condo-gpu' '--gpus=1'"
#     runtime: 1